version: '2'
services:
  web:
    image: nginx:latest
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
    NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
    NGINX_ERROR_LOG_LEVEL: debug
    NGINX_BACKEND_HOST: php
    NGINX_SERVER_ROOT: /var/www/html
  php:
    image: drupal:8.3-fpm
    environment:
      DB_HOST:postgresql
      DB_USER:test
      DB_PASSWORD:test
      DB_NAME:testbase
    links:
      - postgresql:mysql
    volumes:
      - drupal-install:/var/www/html
  db:
    image: postgresql:latest
    environment:
      POSTGRES_PASSWORD:secret
      POSTGRES_DATABASE:testbase 
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:3.2
